### PR TITLE
New DLite Datamodel for SingleFile that contains 'content'

### PR DESCRIPTION
**Pull request by francescalb**
datanode2cuds updated to populate this new version of SingleFile.

The reason for this is that we need to be able to access the data in the datanodes in the next partial pipeline

Missing tests, but I did not find any tests for aiida-cuds to lean on.

### CODE REVIEW

**Comment by francescalb** [comment]
@louisponet @CasperWA 

Louis and I both have old PRs that should have been merged.
Now that Casper has made an update of execflow to match the newest version of oteapi which uses pydantic2 instead of 1 I wanted to make use of all changes.

Unfortunately trying to merge all branches ended up in a mess for me, so I took only the important parts from my branch, merged with Caspers and then afterwards added all Louis updates (the latter without merge).

I hope this is OK with both of you so that we can proceed. Now all the tests in Execflow run again, and I can run everything that worked before in SS3_wrappers.

This is priabbly not the correct procedure to make such changes, but at the end of the day this was the way I managed. 

There are some things that need to be fixed: The critical things to correct prior to merging described in https://github.com/H2020-OpenModel/ExecFlow/pull/22, and fixing of the possibility to define processors etc in the workflow as the original fix did not work.

**Comment by CasperWA** [comment]
This all seems fine with me, but then again, it's not my contributions that have been wiped away.
As a suggestion, you could add `Co-authored-by: Louis Ponet <louis.ponet@epfl.ch>` (if that's the correct email address) to the commits that implement his changes to provide him with some acknowledgement of his work?

**Review by louisponet — APPROVED** [review]
Lots of changes, looks good to me. As a side node for future observability I’d separate extensive reformatting from actual code PRs. Anyhow thanks for the work to the both of you! Don’t worry about wiping my commit authorship, it’s the final result that counts!

**Comment by louisponet** [comment]
Shall I close the other PR from you @CasperWA ?

**Pull request merged**
